name: Notify Me

on:
  workflow_run:
    workflows: ["Test and Build", "Deploy mdBook site to Pages"]
    types:
      - completed
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Me Through Telegram
        uses: Snr1s3/notify-telegram-action@v1.0.1
        with:
          telegram_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          telegram_chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
